#!/usr/bin/env ruby

require 'bundler/setup'

require 'readline'
require 'awesome_print'

require_relative 'lib/rpn/processor.rb'

def each_line
  running = true
  while running
    begin
      while line = Readline.readline('> ', true)
        yield line
      end
      running = false
    rescue Interrupt
      puts
    rescue StandardError => e
      warn e.message + "\n" + e.backtrace.map { |trace_line| '    ' + trace_line }.join("\n")
    end
  end
end

processor = Rpn::Processor.new

each_line do |line|
  begin
    unless line.empty?
      processor.append_string line
      processor.process
    end
  rescue Interrupt
    puts
  end
end
