#!/usr/bin/env ruby

require 'readline'
require 'awesome_print'

require_relative 'lib/rpn/processor.rb'

stty_save = `stty -g`.chomp

def each_line
  running = true
  while running
    begin
      while line = Readline.readline('> ', true)
        yield line
      end
      running = false
    rescue Interrupt => e
      puts
    rescue StandardError => e
      warn e.message + "\n" + e.backtrace.map { |line| '    ' + line }.join("\n")
    end
  end
end

processor = Rpn::Processor.new

each_line do |line|
  begin
    processor.append_string line
    processor.process
    ap processor.result_stack
  rescue Interrupt => e
    puts
  end
end
